// Demo presets for one-click testing
export const DEMO_PRESETS = [
  {
    id: 'demo_aura_skin',
    name: 'Aura Skin — Morning Reset',
    tagline: '30s Instagram Ad for Gen Z Luxury Skincare',
    brief: {
      contentType: 'instagram_ad',
      product: 'Aura Glow Serum',
      productDescription: 'Organic botanical glow serum with hyaluronic acid and niacinamide in an amber glass dropper.',
      audience: 'Gen Z / Young Professionals (18-28)',
      visualStyle: 'Cinematic, authentic, soft warm morning lighting, natural skin texture',
      duration: 30,
      priority: { quality: 0.6, cost: 0.2, speed: 0.2 }
    },
    brandDNA: {
      brandName: 'Aura Skin',
      colors: ['#F5E6D3', '#8B7355', '#FFFFFF'],
      tone: ['premium', 'authentic', 'minimal'],
      restrictions: [
        'Avoid high-saturation neon colors',
        'Maintain natural skin texture (no plastic AI blur)',
        'Preserve amber glass bottle packaging exactly'
      ]
    },
    workflow: {
      metadata: { totalCost: 1.84, totalTime: 260, qualityScore: 9.1 },
      nodes: [
        {
          id: 'node_brief',
          type: 'custom',
          position: { x: 280, y: 0 },
          data: {
            label: 'Creative Brief',
            type: 'brief',
            status: 'completed',
            estimatedCost: 0.0,
            estimatedTime: 0,
            prompt: 'Instagram 30s Ad for Aura Glow Serum, Gen Z, authentic morning reset theme.',
          },
        },
        {
          id: 'node_director',
          type: 'custom',
          position: { x: 280, y: 120 },
          data: {
            label: 'Creative Director Agent',
            type: 'agent',
            status: 'completed',
            model: { name: 'GPT-OSS 120B (Groq)', provider: 'Groq' },
            modelReason: 'Selected for structured campaign ideation and multi-scene storyboard drafting',
            estimatedCost: 0.02,
            estimatedTime: 5,
          },
        },
        {
          id: 'node_scene1_img',
          type: 'custom',
          position: { x: 80, y: 260 },
          data: {
            label: 'Scene 1: Morning Mirror',
            type: 'image_generation',
            status: 'completed',
            model: { name: 'Flux Pro', provider: 'Black Forest Labs' },
            modelReason: 'Highest photorealism for skin texture in soft natural light',
            estimatedCost: 0.08,
            estimatedTime: 14,
            prompt: 'Close-up portrait of a woman looking in the mirror, soft natural morning sunlight, authentic skin texture.',
            brandCheck: { passed: true, message: 'Adheres to authentic lighting and texture guidelines' },
          },
        },
        {
          id: 'node_scene2_img',
          type: 'custom',
          position: { x: 480, y: 260 },
          data: {
            label: 'Scene 2: Product Reveal',
            type: 'image_generation',
            status: 'completed',
            model: { name: 'Flux Pro', provider: 'Black Forest Labs' },
            modelReason: 'Precise product fidelity for luxury amber glass bottle',
            estimatedCost: 0.08,
            estimatedTime: 14,
            prompt: 'Hero shot of Aura Glow Serum amber bottle with minimalist typography, warm backlight, water droplets.',
            brandCheck: { passed: true, message: 'Packaging and brand palette verified' },
          },
        },
        {
          id: 'node_video_gen',
          type: 'custom',
          position: { x: 180, y: 420 },
          data: {
            label: 'Cinematic Motion Gen',
            type: 'video_generation',
            status: 'ready',
            model: { name: 'Runway Gen-3 Alpha', provider: 'Runway' },
            modelReason: 'Industry standard for high-fidelity fluid camera motion',
            estimatedCost: 0.45,
            estimatedTime: 45,
            prompt: 'Smooth macro pan across serum droplets and morning light reflection.',
          },
        },
        {
          id: 'node_voice',
          type: 'custom',
          position: { x: 480, y: 420 },
          data: {
            label: 'Voiceover Synthesis',
            type: 'audio_generation',
            status: 'ready',
            model: { name: 'ElevenLabs Multilingual v2', provider: 'ElevenLabs' },
            modelReason: 'Natural conversational cadence matching Gen Z target audience',
            estimatedCost: 0.12,
            estimatedTime: 8,
            prompt: '"Your morning routine just changed. Meet Aura Glow."',
          },
        },
        {
          id: 'node_export',
          type: 'custom',
          position: { x: 330, y: 560 },
          data: {
            label: 'Final Ad Assembly & Export',
            type: 'export',
            status: 'ready',
            estimatedCost: 0.0,
            estimatedTime: 10,
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node_brief', target: 'node_director', animated: true },
        { id: 'e2-3', source: 'node_director', target: 'node_scene1_img' },
        { id: 'e2-4', source: 'node_director', target: 'node_scene2_img' },
        { id: 'e3-5', source: 'node_scene1_img', target: 'node_video_gen' },
        { id: 'e4-5', source: 'node_scene2_img', target: 'node_video_gen' },
        { id: 'e2-6', source: 'node_director', target: 'node_voice' },
        { id: 'e5-7', source: 'node_video_gen', target: 'node_export' },
        { id: 'e6-7', source: 'node_voice', target: 'node_export' },
      ],
    }
  },
  {
    id: 'demo_nova_audio',
    name: 'Nova Pro — Sound Unleashed',
    tagline: 'High-Energy Cyberpunk Product Film for Flagship ANC Headphones',
    brief: {
      contentType: 'cinematic_film',
      product: 'Nova Pro ANC Headphones',
      productDescription: 'Matte titanium wireless headphones with active noise cancellation and luminous acoustic mesh.',
      audience: 'Audiophiles, Creators, Tech Enthusiasts (20-35)',
      visualStyle: 'Sleek dark futuristic, dramatic rim lighting, neon indigo accents, dynamic speed ramps',
      duration: 45,
      priority: { quality: 0.7, cost: 0.15, speed: 0.15 }
    },
    brandDNA: {
      brandName: 'Nova Audio',
      colors: ['#0A0A0F', '#6366F1', '#E2E8F0'],
      tone: ['bold', 'futuristic', 'premium', 'high-tech'],
      restrictions: [
        'Avoid warm sepia or vintage filters',
        'Emphasize precision engineering and acoustic mesh detail',
        'No rustic or handheld shaky cam'
      ]
    },
    workflow: {
      metadata: { totalCost: 2.10, totalTime: 310, qualityScore: 9.4 },
      nodes: [
        {
          id: 'node_brief',
          type: 'custom',
          position: { x: 280, y: 0 },
          data: {
            label: 'Creative Brief',
            type: 'brief',
            status: 'completed',
            estimatedCost: 0.0,
            estimatedTime: 0,
            prompt: 'Cinematic 45s product film for Nova Pro ANC Headphones, high tech aesthetic.',
          },
        },
        {
          id: 'node_director',
          type: 'custom',
          position: { x: 280, y: 120 },
          data: {
            label: 'Creative Director Agent',
            type: 'agent',
            status: 'completed',
            model: { name: 'GPT-OSS 120B (Groq)', provider: 'Groq' },
            modelReason: 'Selected for high-energy storyboarding and sound-design cues',
            estimatedCost: 0.03,
            estimatedTime: 6,
          },
        },
        {
          id: 'node_render_3d',
          type: 'custom',
          position: { x: 80, y: 260 },
          data: {
            label: 'Titanium Exploded View',
            type: 'image_generation',
            status: 'completed',
            model: { name: 'Midjourney v6.1 / Flux Pro', provider: 'BFL' },
            modelReason: 'Exceptional hard-surface metallic rendering and depth',
            estimatedCost: 0.10,
            estimatedTime: 18,
            prompt: 'Exploded technical 3D view of titanium earcups, acoustic drivers floating, indigo rim lighting.',
            brandCheck: { passed: true, message: 'Dark aesthetic and engineering focus verified' },
          },
        },
        {
          id: 'node_lifestyle_img',
          type: 'custom',
          position: { x: 480, y: 260 },
          data: {
            label: 'Cyber City Lifestyle',
            type: 'image_generation',
            status: 'completed',
            model: { name: 'Flux Pro', provider: 'BFL' },
            modelReason: 'High dynamic range night cityscape portrait with edge glow',
            estimatedCost: 0.08,
            estimatedTime: 15,
            prompt: 'Portrait of music producer wearing Nova Pro in rainy neon-lit city studio.',
            brandCheck: { passed: true, message: 'Futuristic tone verified' },
          },
        },
        {
          id: 'node_video_gen',
          type: 'custom',
          position: { x: 180, y: 420 },
          data: {
            label: 'Speed Ramp Motion Gen',
            type: 'video_generation',
            status: 'ready',
            model: { name: 'Kling 1.5 Pro', provider: 'Kling' },
            modelReason: 'Superior 3D spatial rotation and temporal consistency',
            estimatedCost: 0.55,
            estimatedTime: 50,
            prompt: 'Orbiting camera rotating 360 around headphones as sound waves distort the background.',
          },
        },
        {
          id: 'node_voice',
          type: 'custom',
          position: { x: 480, y: 420 },
          data: {
            label: 'Punchy Cinematic Voiceover',
            type: 'audio_generation',
            status: 'ready',
            model: { name: 'ElevenLabs Turbo v2.5', provider: 'ElevenLabs' },
            modelReason: 'Deep resonant cinematic narrator tone',
            estimatedCost: 0.14,
            estimatedTime: 9,
            prompt: '"Silence the noise. Unleash the pure spectrum."',
          },
        },
        {
          id: 'node_export',
          type: 'custom',
          position: { x: 330, y: 560 },
          data: {
            label: 'Final Master Export',
            type: 'export',
            status: 'ready',
            estimatedCost: 0.0,
            estimatedTime: 12,
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'node_brief', target: 'node_director', animated: true },
        { id: 'e2-3', source: 'node_director', target: 'node_render_3d' },
        { id: 'e2-4', source: 'node_director', target: 'node_lifestyle_img' },
        { id: 'e3-5', source: 'node_render_3d', target: 'node_video_gen' },
        { id: 'e4-5', source: 'node_lifestyle_img', target: 'node_video_gen' },
        { id: 'e2-6', source: 'node_director', target: 'node_voice' },
        { id: 'e5-7', source: 'node_video_gen', target: 'node_export' },
        { id: 'e6-7', source: 'node_voice', target: 'node_export' },
      ],
    }
  }
]

export const auraSkinDemoWorkflow = DEMO_PRESETS[0].workflow
