export const auraSkinDemoWorkflow = {
  metadata: {
    totalCost: 1.84,
    totalTime: 260,
    qualityScore: 9.1,
  },
  nodes: [
    {
      id: 'node_brief',
      type: 'custom',
      position: { x: 250, y: 0 },
      data: {
        label: 'Creative Brief',
        type: 'brief',
        status: 'completed',
        estimatedCost: 0.0,
        estimatedTime: 0,
        prompt: 'Instagram 30s Ad for Aura Glow Serum, Gen Z, authentic morning reset theme.',
      },
    },
    {
      id: 'node_director',
      type: 'custom',
      position: { x: 250, y: 120 },
      data: {
        label: 'Creative Director Agent',
        type: 'agent',
        status: 'completed',
        model: { name: 'Llama 3.3 70B (Groq)', provider: 'Groq' },
        modelReason: 'Selected for nuanced creative planning and storyboard drafting',
        estimatedCost: 0.02,
        estimatedTime: 5,
      },
    },
    {
      id: 'node_scene1_img',
      type: 'custom',
      position: { x: 50, y: 260 },
      data: {
        label: 'Scene 1: Morning Mirror',
        type: 'image_generation',
        status: 'completed',
        model: { name: 'Flux Pro', provider: 'Black Forest Labs' },
        modelReason: 'Highest photorealism for skin texture in soft natural light',
        estimatedCost: 0.08,
        estimatedTime: 14,
        prompt: 'Close-up portrait of a woman looking in the mirror, soft natural morning sunlight, authentic skin texture.',
        brandCheck: { passed: true, message: 'Adheres to authentic lighting and texture guidelines' },
      },
    },
    {
      id: 'node_scene2_img',
      type: 'custom',
      position: { x: 450, y: 260 },
      data: {
        label: 'Scene 2: Product Hero Reveal',
        type: 'image_generation',
        status: 'completed',
        model: { name: 'Flux Pro', provider: 'Black Forest Labs' },
        modelReason: 'Precise product fidelity for luxury amber glass bottle',
        estimatedCost: 0.08,
        estimatedTime: 14,
        prompt: 'Hero shot of Aura Glow Serum amber bottle with minimalist typography, warm backlight, water droplets.',
        brandCheck: { passed: true, message: 'Packaging and brand palette verified' },
      },
    },
    {
      id: 'node_video_gen',
      type: 'custom',
      position: { x: 150, y: 420 },
      data: {
        label: 'Cinematic Motion Gen',
        type: 'video_generation',
        status: 'ready',
        model: { name: 'Runway Gen-3 Alpha', provider: 'Runway' },
        modelReason: 'Industry standard for high-fidelity fluid camera motion',
        estimatedCost: 0.45,
        estimatedTime: 45,
        prompt: 'Smooth macro pan across serum droplets and morning light reflection.',
      },
    },
    {
      id: 'node_voice',
      type: 'custom',
      position: { x: 450, y: 420 },
      data: {
        label: 'Voiceover Synthesis',
        type: 'audio_generation',
        status: 'ready',
        model: { name: 'ElevenLabs Multilingual v2', provider: 'ElevenLabs' },
        modelReason: 'Natural conversational cadence matching Gen Z target audience',
        estimatedCost: 0.12,
        estimatedTime: 8,
        prompt: '"Your morning routine just changed. Meet Aura Glow."',
      },
    },
    {
      id: 'node_export',
      type: 'custom',
      position: { x: 300, y: 560 },
      data: {
        label: 'Final Ad Assembly & Export',
        type: 'export',
        status: 'ready',
        estimatedCost: 0.0,
        estimatedTime: 10,
      },
    },
  ],
  edges: [
    { id: 'e1-2', source: 'node_brief', target: 'node_director', animated: true },
    { id: 'e2-3', source: 'node_director', target: 'node_scene1_img' },
    { id: 'e2-4', source: 'node_director', target: 'node_scene2_img' },
    { id: 'e3-5', source: 'node_scene1_img', target: 'node_video_gen' },
    { id: 'e4-5', source: 'node_scene2_img', target: 'node_video_gen' },
    { id: 'e2-6', source: 'node_director', target: 'node_voice' },
    { id: 'e5-7', source: 'node_video_gen', target: 'node_export' },
    { id: 'e6-7', source: 'node_voice', target: 'node_export' },
  ],
}
